from typing import TypedDict, Annotated, List
from langgraph.graph import StateGraph, START, END
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
import operator

llm = ChatOllama(model="gemma4")

class State(TypedDict):
    tracker: str # Tracks summary in a simple structured way
    # Not in use yet
    """T
    Iter 1
    ======
    PM said this
    Coder said this
    QA said this
    """

    messages: Annotated[list, operator.add]
    task: str # Stores the original query
    plan: str # Stores the plan generated by the PM

    code: str # Stores the code generated by the coder
    feedback: str # Stores the feedback from QA
    iterations: int

class PROMPTS:
    pm_agent = "Be very brief. You are a Product Manager. You only plan and do not write code."
    code_agent = "Be very brief. You are a efficient senior developer. Return only the code block. No description. No explanation."
    qa_agent = "Be very brief. You are a QA agent. Be deliberately difficult in assessment. Either say 'PASSED' or provide feedback to redo. Nothing else."

def pm_agent(state: State):
    query = state['messages'][-1]
    system = SystemMessage(content=PROMPTS.pm_agent)

    response = llm.invoke([system, query])
    return {"task":query.content, "plan":response.content, "messages": [response], "iterations": 0}

def code_agent(state: State):
    system = SystemMessage(content=PROMPTS.code_agent)


    plan = state["plan"]
    feedback = state.get("feedback", "")
    plan += f"\n\n[CRITICAL CORRECTION FROM QA]:" + feedback

    response = llm.invoke([system, plan])
    return {"code": response.content , "messages": [response]}

def qa_agent(state: State):
    system = SystemMessage(content=PROMPTS.qa_agent)
    plan = state["plan"]
    code  = state["code"]

    response = llm.invoke([system, plan, code])
    return {"messages": [response], "feedback": response.content, "iterations": state["iterations"] + 1}


def agent(state: State):
    prompt = state['messages'][-1]
    system = SystemMessage(content="You are a helpful assistant.")

    response = llm.invoke([system, prompt])
    return {"messages": [response]}

workflow = StateGraph(State)
workflow.add_node("pm", pm_agent)
workflow.add_node("code", code_agent)
workflow.add_node("qa", qa_agent)

workflow.add_edge(START, "pm")
workflow.add_edge("pm", "code")
workflow.add_edge("code", "qa")

def check_passed(state: State):
    if "PASSED" in state["feedback"]: return END
    if state["iterations"] > 3: return END
    else: return "code"

workflow.add_conditional_edges("qa", check_passed)


app = workflow.compile()

initial_state = {
    "messages": [HumanMessage(content="Write a Python function process_invoice that takes a list of strings. It must sum numerical values as a subtotal. If a string contains a '%' sign, treat it as a tax rate for the current subtotal. If a string starts with a '-', subtract it as a flat discount after tax. Return the breakdown in a dictionary.")]
}

final = app.invoke(initial_state)
for msg in final["messages"]:
    print("✅", type(msg).__name__, ":", msg.content)
